from __future__ import annotations

ANALYSIS_STATES = {"ACTIVE", "BLOCKED", "COMPLETE"}
ANALYSIS_STATUSES = {"CONFIRMED", "HIGH_CONFIDENCE", "CANDIDATE", "REJECTED", "UNRESOLVED"}
MESSAGE_DIRECTIONS = {"C2S", "S2C", "unknown"}
